{
 "title": "Основной дашборд разработки",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Базовый запрос на селект всего",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select * from vm_data.vm_metrics where date_time > $__timeFrom() and date_time < $__timeTo()"
    }
   ]
  },
  {
   "title": "Стоимость виртуальных машин",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "р" } },
   "targets": [
    {
     "rawSql": "\r\nselect $__timeGroupAlias(date_time, 1m),\r\nvm_name, vm_price_min as \"Стоимость в минуту\"\r\nFROM vm_data.vm_metrics\r\nWHERE\r\n$__timeFilter(date_time)\r\nGROUP BY 1, vm_name, \"Стоимость в минуту\"\r\nORDER BY $__timeGroup(date_time, 1m)"
    }
   ]
  },
  {
   "title": "Стоимость виртуальных машин",
   "type": "table",
   "gridPos": { "h": 24, "w": 17, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "select vm_name as \"vm\", vm_state, avg(vm_price_min) as \"price_for_min\", sum(vm_price_min) as \"price_for_period\", avg(vm_price_min) * 60 * 24 * 30 as \"vm_price_mon_expect\" from vm_data.vm_metrics \r\nwhere date_time > $__timeFrom() and date_time < $__timeTo() \r\ngroup by vm_name, vm_state\r\norder by \"price_for_period\" desc"
    }
   ]
  },
  {
   "title": "Общая стоимость за период",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "р" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(price_for_period) as \"total_price_mon_expect\" from \r\n  (select vm_name as \"vm\", avg(vm_price_min) as \"price_for_min\", sum(vm_price_min) as \"price_for_period\", avg(vm_price_min) * 60 * 24 * 30 as \"vm_price_mon_expect\" from vm_data.vm_metrics \r\n  where date_time > $__timeFrom() and date_time < $__timeTo() \r\n  group by vm_name\r\n  order by \"price_for_period\" desc) as t1"
    }
   ]
  },
  {
   "title": "Общая ожидаемая стоимость в месяц",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "р" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(vm_price_mon_expect) as \"total_price_mon_expect\" from \r\n  (select vm_name as \"vm\", avg(vm_price_min) as \"price_for_min\", sum(vm_price_min) as \"price_for_period\", avg(vm_price_min) * 60 * 24 * 30 as \"vm_price_mon_expect\" from vm_data.vm_metrics \r\n  where date_time > $__timeFrom() and date_time < $__timeTo() \r\n  group by vm_name\r\n  order by \"price_for_period\" desc) as t1"
    }
   ]
  },
  {
   "title": "Топ-10 серверов с максимальной стоимостью за период",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 7, "x": 17, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "р" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select vm_name as \"vm\", sum(vm_price_min) as \"price_for_period\" from vm_data.vm_metrics \r\nwhere date_time > $__timeFrom() and date_time < $__timeTo() \r\ngroup by vm_name\r\norder by \"price_for_period\" desc\r\nlimit 10"
    }
   ]
  },
  {
   "title": "Стоимость виртуальных машин",
   "type": "table",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "rawSql": "select \r\n\tvmm.vm_name as \"vm\", \r\n\tvmm.vm_metadata->>'customer' as \"customer\",\r\n\tvmm.vm_metadata->>'task' as \"task\",\r\n\tvmm.vm_metadata->>'purpose' as \"purpose\",\r\n\tvmm.vm_state, avg(vm_price_min) as \"price_for_min\", \r\n\tsum(vmm.vm_price_min) as \"price_for_period\", \r\n\tavg(vmm.vm_price_min) * 60 * 24 * 30 as \"vm_price_mon_expect\",\r\n\tCASE WHEN vmm.vm_state = 0 THEN '0' ELSE '1' END  as \"vm_control\"\r\nfrom vm_data.vm_metrics vmm \r\njoin (\r\n\tselect \r\n\t\tvm_name, \r\n\t\tmax(date_time) as \"maxtime\"\r\n\tfrom vm_data.vm_metrics\r\n\twhere\r\n\t\tdate_time > $__timeFrom()\r\n\t\tand date_time < $__timeTo()\r\n\tgroup by vm_name\r\n) vmmm on vmm.date_time = vmmm.\"maxtime\"\r\ngroup by vmm.vm_name, vmm.vm_state, vmm.vm_metadata->>'customer', vmm.vm_metadata->>'task', vmm.vm_metadata->>'purpose'\r\norder by \"price_for_period\" desc"
    }
   ]
  }
 ]
}