version: "3.10"
services:
  postgres:
    image: postgres:13.3
    container_name: postgres-vkmon
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "vkmon"
      POSTGRES_USER: "vkmon"
      POSTGRES_PASSWORD: "vkmon"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vkmon -d vkmon"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M

  grafana:
    image: grafana/grafana-oss:10.1.2
    container_name: grafana-vkmon
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./volumes/grafana-data:/var/lib/grafana

  luigi:
    build:
      context: .
      dockerfile: Dockerfile.luigi
    volumes:
      - ./scripts:/scripts
      - ./states:/states
      - ./vkmon.ini:/vkmon.ini
    container_name: scripts-vkmon
    restart: always
